/*
================================================================================
 DeadeyeBot v17.4 — "THE ASYNC FIX"
 (v17.2 Body + v14 Brain)

 WHAT'S FIXED:
 1) ASYNC STARTUP: The v14.2 `perform_startup_sequence` (which used a
    blocking `while` loop) has been completely rewritten.
 2) It is now an ASYNCHRONOUS state machine (`start_startup_sequence_timer`)
    that runs on a timer, just like the splash screen.
 3) This STOPS the main thread from blocking, which fixes the bug:
    - The splash screen WILL now close.
    - The `SCStream` WILL now deliver live video.
    - The bot WILL find the orange button.

 This is the final, non-blocking, merged file.
================================================================================
*/

// ============================ Standard & STL ================================
#include <iostream>
#include <fstream>
#include <sstream>
#include <vector>
#include <string>
#include <chrono>
#include <thread>
#include <map>
#include <set>
#include <cmath>
#include <filesystem>
#include <algorithm>
#include <deque>
#include <atomic>
#include <mutex>

// ================================ OpenCV ====================================
#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

// =========================== Apple Frameworks ===============================
#import <Metal/Metal.h>
#import <CoreGraphics/CoreGraphics.h>
#import <ApplicationServices/ApplicationServices.h>
#import <Foundation/Foundation.h>
#import <AppKit/AppKit.h>
#import <ScreenCaptureKit/ScreenCaptureKit.h>
#import <CoreMedia/CoreMedia.h>
#import <CoreVideo/CoreVideo.h>
#import <Carbon/Carbon.h>
#import <AVFoundation/AVFoundation.h>

// ============== EMBEDDED ASSETS (generated by CMake) ========================
#include "overlay_png.h"
#include "splash_png.h"
#include "bodies_wav.h"

using namespace std::chrono_literals;

// ============================================================================
// v14.2 BOT CONSTANTS
// ============================================================================
static const int RADAR_WIDTH            = 302;
static const int RADAR_HEIGHT           = 655;

static const int UI_TIMER_Y_LIMIT       = 50;
static const int UI_SCORE_Y_LIMIT       = 100;
static const int FALLING_THRESHOLD_Y    = 550;
static const int CANNON_GROUND_Y        = 620;
static const int DESTROY_PIT_Y          = 680;

static const int CANNON_WIDTH           = 75;
static const int CANNON_HEIGHT          = 100;
static const int ROCK_WIDTH             = 40;
static const int ROCK_HEIGHT            = 40;
static const int MIN_SAFE_GAP           = 80;
static const int COLLISION_SAFETY_MARGIN= 5;

static const int   LOW_THREAT_THRESHOLD = 3;
static const float PANIC_TIME           = 0.8f;
static const float FIRE_RATE            = 10.0f;
static const int   STARTING_HP_GUESST   = 9;

static const float GRAVITY              = 400.0f;
static const float ROCK_BOUNCE_DAMPING  = 0.8f;
static const float BULLET_SPEED         = 500.0f;

static const std::string WINDOW_TITLE   = "iPhone Mirroring";

static const std::string CSV_ROCK_LOG   = "deadeye_rock_log.csv";
static const std::string CSV_BOT_LOG    = "deadeye_bot_log.csv";
static const std::string CSV_BULLET_LOG = "deadeye_bullet_log.csv";

// v14.2 HSV ranges
static const cv::Scalar ORANGE_LOW(5, 100, 130);
static const cv::Scalar ORANGE_HIGH(30, 255, 255);
static const cv::Scalar CANNON_HSV_LOW(0, 40, 80);
static const cv::Scalar CANNON_HSV_HIGH(35, 255, 255);

// v14.2 Centered click values
constexpr double BUTTON_X_BIAS_FRAC = 0.5;
constexpr double BUTTON_Y_OFFSET_PX = 0.0;

// v17.2 Overlay scale
static double g_overlayScale = 0.40;


// ============================================================================
// GLOBAL STATE (v17.2 + v14.2 MERGED)
// ============================================================================

// v14.2 Logging
std::ofstream g_rock_log, g_bot_log, g_bullet_log;
std::mutex g_log_mutex;

// v17.2 UI
static CGRect           g_windowRect = CGRectZero;
static std::atomic<bool> g_quit{false};
static AVAudioPlayer* g_splashPlayer = nil;

// v14.2 Metal
id<MTLDevice>                  g_device = nil;
id<MTLComputePipelineState>    g_radarPipeline = nil;
id<MTLCommandQueue>            g_commandQueue = nil;
id<MTLTexture>                 g_debugTexture = nil;
id<MTLTexture>                 g_lastFrameTexture = nil;
id<MTLBuffer>                  g_constantsBuffer = nil;

// v14.2 Mouse
float     g_cannon_y_abs = 0.f;
float     g_mouse_x_abs = 0.f;
bool      g_mouse_held = false;
double    g_last_fire_time = 0.0;

// v14.2 Cannon Watchdog
float g_observed_cannon_x_rel = RADAR_WIDTH/2.0f;
float g_last_observed_x_rel   = -1.0f;
int   g_no_movement_frames    = 0;
int   g_rehold_cooldown       = 0;

// v17.2 ScreenCaptureKit Stream
@interface DEFrameSink : NSObject<SCStreamOutput>
@property (atomic) CVPixelBufferRef latest;
@end
@implementation DEFrameSink
- (instancetype)init { if ((self=[super init])) _latest=nullptr; return self; }
- (void)dealloc { if (_latest) CFRelease(_latest); }
- (void)stream:(SCStream*)s didOutputSampleBuffer:(CMSampleBufferRef)sb ofType:(SCStreamOutputType)type {
    if (type != SCStreamOutputTypeScreen) return;
    CVPixelBufferRef pb=(CVPixelBufferRef)CMSampleBufferGetImageBuffer(sb); if(!pb) return;
    CVPixelBufferRetain(pb);
    CVPixelBufferRef old=_latest; _latest=pb; if(old) CFRelease(old);
}
@end

struct Capture {
    SCStream* stream=nil; DEFrameSink* sink=nil; bool started=false;
    bool start() {
        if (started) return true;
        __block BOOL ok=NO; __block SCShareableContent* content=nil;
        dispatch_semaphore_t sem=dispatch_semaphore_create(0);
        [SCShareableContent getShareableContentWithCompletionHandler:^(SCShareableContent* c, NSError* e){
            content=c; ok=(c && !e && c.displays.count>0); dispatch_semaphore_signal(sem);
        }];
        dispatch_semaphore_wait(sem, DISPATCH_TIME_FOREVER);
        if(!ok) return false;

        SCDisplay* d=content.displays.firstObject;
        SCContentFilter* filter=[[SCContentFilter alloc] initWithDisplay:d excludingApplications:@[] exceptingWindows:@[]];

        SCStreamConfiguration* cfg=[SCStreamConfiguration new];
        cfg.showsCursor=NO; cfg.capturesAudio=NO; cfg.pixelFormat=kCVPixelFormatType_32BGRA;
        cfg.width=d.width; cfg.height=d.height;

        sink=[DEFrameSink new];
        stream=[[SCStream alloc] initWithFilter:filter configuration:cfg delegate:nil];

        NSError* err=nil;
        if(![stream addStreamOutput:sink type:SCStreamOutputTypeScreen
             sampleHandlerQueue:dispatch_get_global_queue(QOS_CLASS_USER_INTERACTIVE,0) error:&err]) return false;

        __block BOOL startedOK=NO; dispatch_semaphore_t sem2=dispatch_semaphore_create(0);
        [stream startCaptureWithCompletionHandler:^(NSError* e){ startedOK=(e==nil); dispatch_semaphore_signal(sem2);}];
        dispatch_semaphore_wait(sem2, DISPATCH_TIME_FOREVER);
        started = startedOK;
        return startedOK;
    }

    cv::Mat latest_cropped_downscaled() {
        CVPixelBufferRef pb = sink ? sink.latest : nil;
        if(!pb) return {};

        // Retain the buffer to prevent it from being released while we use it
        CFRetain(pb);

        // Try to lock - if it fails, the buffer is invalid
        CVReturn lockResult = CVPixelBufferLockBaseAddress(pb, kCVPixelBufferLock_ReadOnly);
        if(lockResult != kCVReturnSuccess) {
            CFRelease(pb);
            return {};
        }

        size_t W=CVPixelBufferGetWidth(pb), H=CVPixelBufferGetHeight(pb), stride=CVPixelBufferGetBytesPerRow(pb);
        uint8_t* base=(uint8_t*)CVPixelBufferGetBaseAddress(pb);
        if(!base){
            CVPixelBufferUnlockBaseAddress(pb, kCVPixelBufferLock_ReadOnly);
            CFRelease(pb);
            return {};
        }
        cv::Mat bgra((int)H,(int)W,CV_8UC4,base,stride);

        CGRect r=g_windowRect; // TOP-left coordinate rect
        int x=std::max(0,(int)r.origin.x), y=std::max(0,(int)r.origin.y);
        int cw=std::min<int>((int)r.size.width,(int)W-x);
        int ch=std::min<int>((int)r.size.height,(int)H-y);

        cv::Mat crop;
        if (cw>1 && ch>1) crop = bgra(cv::Rect(x,y,cw,ch)).clone();
        CVPixelBufferUnlockBaseAddress(pb, kCVPixelBufferLock_ReadOnly);
        CFRelease(pb);

        if (crop.empty()) return {};
        cv::Mat bgr; cv::cvtColor(crop,bgr,cv::COLOR_BGRA2BGR);
        cv::resize(bgr,bgr,cv::Size(RADAR_WIDTH,RADAR_HEIGHT),0,0,cv::INTER_LINEAR);
        return bgr;
    }
};
static Capture g_cap;

// v17.2 Overlay UI
@interface DeadeyeOverlay : NSWindow @end
@implementation DeadeyeOverlay @end
static DeadeyeOverlay* g_overlayWin = nil;
static NSImageView* g_overlayView = nil;
static NSImage* g_overlayImage = nil;

// v17.2 Debug UI
@interface DebugWindow : NSWindow @end
@implementation DebugWindow @end
static DebugWindow* g_debugWin  = nil;
static NSImageView* g_debugView = nil;
static int           g_dbgW = 360;
static int           g_dbgH = 800;

// v17.2 Splash UI
@interface DeadeyeSplash : NSWindow @end
@implementation DeadeyeSplash @end
static DeadeyeSplash* g_splashWin = nil;
static NSTextField* g_splashLabel = nil;
static NSImageView* g_splashArtView = nil;
static NSImage* g_splashArt = nil;

// v17.2 Kill Switch
static CFMachPortRef g_tap=nullptr; static CFRunLoopSourceRef g_tapSrc=nullptr;

// v17.4 ASYNC STARTUP STATE
enum class StartupState {
    LookingForButton,
    ButtonClicked,
    LookingForCannon,
    Done
};
static StartupState g_startupState = StartupState::LookingForButton;
static double g_startupRetryCheckTime = 0.0;
static cv::Rect g_foundButtonRect;
static dispatch_source_t g_startup_timer = nil;
static dispatch_source_t g_bot_logic_timer = nil;


// ============================================================================
// v14.2 BOT DATA STRUCTURES
// ============================================================================
struct BulletState {
    int   id;
    float x, y;
    float vx, vy;
    double fired_time;
    bool  active;
};

struct CollisionBox {
    float x_min, x_max;
    float y_min, y_max;
    bool overlaps(const CollisionBox& other) const {
        return !(x_max < other.x_min || x_min > other.x_max ||
                 y_max < other.y_min || y_min > other.y_max);
    }
};

struct RockState {
    int          id;
    cv::Rect     bbox;
    cv::Point2f  center;
    cv::Point2f  velocity;
    int          hp;
    int          original_hp;
    double       last_seen;
    double       time_to_ground;
    float        predicted_x;
    bool         is_tracked;
    bool         is_split_child;

    enum class Type { FALLING, LANDED, DESTROYED };
    Type type;

    CollisionBox get_collision_box() const {
        return {
            center.x - ROCK_WIDTH/2.0f, center.x + ROCK_WIDTH/2.0f,
            center.y - ROCK_HEIGHT/2.0f, center.y + ROCK_HEIGHT/2.0f
        };
    }
    bool is_falling() const { return type == Type::FALLING; }
    bool is_landed()  const { return type == Type::LANDED; }
    bool is_at_cannon_level() const {
        return std::abs(center.y - CANNON_GROUND_Y) < 30;
    }
};

struct BouncePoint { float x, y, time; enum Type { WALL_LEFT, WALL_RIGHT, GROUND, NONE }; Type bounce_type; };
struct TrajectoryPrediction {
    std::vector<BouncePoint> bounces;
    std::vector<std::pair<float, float>> ground_crossings;
    bool  is_stable = false;
    float max_x = 0.f, min_x = 0.f;
};

struct SafeZone {
    float  x_center, x_min, x_max, width;
    bool   is_permanent;
    double safe_until;
};

struct BotDecision {
    std::string priority = "INIT";
    std::string strategy = "PATROL";
    std::string decision = "INIT";
    float       target_x_rel = RADAR_WIDTH / 2.0f;
};

// v14.2 Databases
std::map<int, RockState> g_rock_database;
std::deque<BulletState>  g_bullets;
int  g_next_rock_id = 0;
int  g_next_bullet_id = 0;
int  g_last_destroyed_hp = STARTING_HP_GUESST - 1;
int  g_pending_split_children = 0;
int  g_split_child_hp = 0;


// ============================================================================
// v17.2 UTILITY FUNCTIONS
// ============================================================================
static inline double nowSec() {
    using namespace std::chrono;
    return duration<double>(steady_clock::now().time_since_epoch()).count();
}

// v14.2 Log helper
void log_line(const std::string& s) {
    std::lock_guard<std::mutex> lk(g_log_mutex);
    std::cout << s << std::endl;
}

// ---------- v17.2 Desktop/multi-monitor safe coordinate helpers ----------
static inline CGFloat desktopTopMostY() {
    CGFloat top = -CGFLOAT_MAX;
    for (NSScreen* s in [NSScreen screens]) {
        top = std::max(top, NSMaxY(s.frame)); // Cocoa coords (bottom origin)
    }
    return top; // highest Y across the desktop in Cocoa coord space
}

static inline CGFloat toEventY_FromTop(CGFloat topY) {
    return desktopTopMostY() - topY;
}

static inline CGFloat cocoaOriginY_FromTop(CGFloat topY, CGFloat height) {
    return desktopTopMostY() - (topY + height);
}

// v17.2 Window info lookup
struct WindowInfo { CGRect rect; pid_t pid; uint64_t wid; bool valid; };

static WindowInfo find_window_info(const char* title) {
    WindowInfo out{{0,0,0,0},0,0,false};
    CFArrayRef wl = CGWindowListCopyWindowInfo(
        kCGWindowListOptionOnScreenOnly | kCGWindowListExcludeDesktopElements,
        kCGNullWindowID);
    if (!wl) return out;

    CFStringRef tRef = CFStringCreateWithCString(kCFAllocatorDefault, title, kCFStringEncodingUTF8);
    CFIndex n = CFArrayGetCount(wl);
    for (CFIndex i=0;i<n;i++) {
        auto info = (CFDictionaryRef)CFArrayGetValueAtIndex(wl,i);
        CFStringRef name = (CFStringRef)CFDictionaryGetValue(info, kCGWindowName);
        if (!name || !CFEqual(name, tRef)) continue;

        CFDictionaryRef bdict = (CFDictionaryRef)CFDictionaryGetValue(info, kCGWindowBounds);
        CGRect r = CGRectZero; if (bdict) CGRectMakeWithDictionaryRepresentation(bdict, &r);

        CFNumberRef pidNum = (CFNumberRef)CFDictionaryGetValue(info, kCGWindowOwnerPID);
        int pid=0; if (pidNum) CFNumberGetValue(pidNum, kCFNumberIntType, &pid);

        CFNumberRef widNum = (CFNumberRef)CFDictionaryGetValue(info, kCGWindowNumber);
        long long wid=0; if (widNum) CFNumberGetValue(widNum, kCFNumberLongLongType, &wid);

        out.rect=r; out.pid=(pid_t)pid; out.wid=(uint64_t)wid; out.valid=true;
        break;
    }
    CFRelease(tRef); CFRelease(wl); return out;
}

static bool activate_app_by_pid(pid_t pid) {
    NSRunningApplication* owner = [NSRunningApplication runningApplicationWithProcessIdentifier:pid];
    if (owner) [owner activateWithOptions:NSApplicationActivateAllWindows];
    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
    [NSApp activateIgnoringOtherApps:YES];
    return true;
}


// v17.2 Radar -> Absolute helpers
static inline CGFloat wx(float rx){
    return g_windowRect.origin.x + (rx * (g_windowRect.size.width  / RADAR_WIDTH));
}
static inline CGFloat wy_event(float ry){
    CGFloat topY = g_windowRect.origin.y + (ry * (g_windowRect.size.height / RADAR_HEIGHT)); // TOP-origin
    return toEventY_FromTop(topY); // CGEvent bottom-origin
}


// ============================================================================
// v14.2 MOUSE CONTROL (Ported)
// ============================================================================
void move_mouse(float abs_x,float abs_y){
    g_mouse_x_abs=abs_x;
    CGEventRef e=g_mouse_held ?
      CGEventCreateMouseEvent(nullptr,kCGEventLeftMouseDragged,CGPointMake(abs_x,abs_y),kCGMouseButtonLeft) :
      CGEventCreateMouseEvent(nullptr,kCGEventMouseMoved,CGPointMake(abs_x,abs_y),kCGMouseButtonLeft);
    CGEventPost(kCGHIDEventTap,e); CFRelease(e);
}

void click_and_hold(float abs_x,float abs_y){
    move_mouse(abs_x,abs_y);
    CGEventRef d=CGEventCreateMouseEvent(nullptr,kCGEventLeftMouseDown,CGPointMake(abs_x,abs_y),kCGMouseButtonLeft);
    CGEventPost(kCGHIDEventTap,d); CFRelease(d);
    g_mouse_held=true;
}

void release_mouse(){
    CGEventRef u=CGEventCreateMouseEvent(nullptr,kCGEventLeftMouseUp,CGPointMake(g_mouse_x_abs,g_cannon_y_abs),kCGMouseButtonLeft);
    CGEventPost(kCGHIDEventTap,u); CFRelease(u);
    g_mouse_held=false;
}

void click_once(float abs_x,float abs_y){
    CGEventRef d=CGEventCreateMouseEvent(nullptr,kCGEventLeftMouseDown,CGPointMake(abs_x,abs_y),kCGMouseButtonLeft);
    CGEventRef u=CGEventCreateMouseEvent(nullptr,kCGEventLeftMouseUp,CGPointMake(abs_x,abs_y),kCGMouseButtonLeft);
    CGEventPost(kCGHIDEventTap,d); 
    usleep(30000); // 30ms
    CGEventPost(kCGHIDEventTap,u);
    CFRelease(d); CFRelease(u);
}

void keep_mouse_held(){
    static auto last=std::chrono::steady_clock::now();
    auto now=std::chrono::steady_clock::now();
    if(std::chrono::duration_cast<std::chrono::milliseconds>(now-last).count()>200){
        move_mouse(g_mouse_x_abs,g_cannon_y_abs);
        last=now;
    }
}

static CGPoint currentMouse(){
    CGEventRef ev = CGEventCreate(nullptr);
    CGPoint p = CGEventGetLocation(ev);
    CFRelease(ev);
    return p;
}


// ============================================================================
// v17.2 UI (SPLASH, OVERLAY, DEBUG)
// ============================================================================

// ===== v17.2 Overlay =====
static NSInteger overlayLevel() { return NSStatusWindowLevel; }

static void ensure_overlay_created() {
    if (g_overlayWin) return;
    NSRect r = NSMakeRect(100,100,200,200);
    g_overlayWin = [[DeadeyeOverlay alloc]
        initWithContentRect:r
                  styleMask:NSWindowStyleMaskBorderless
                    backing:NSBackingStoreBuffered
                      defer:NO];
    g_overlayWin.opaque = NO;
    g_overlayWin.backgroundColor = NSColor.clearColor;
    g_overlayWin.level = overlayLevel();
    g_overlayWin.ignoresMouseEvents = YES;
    g_overlayWin.collectionBehavior =
        NSWindowCollectionBehaviorCanJoinAllSpaces |
        NSWindowCollectionBehaviorTransient;

    g_overlayView = [[NSImageView alloc] initWithFrame:r];
    g_overlayView.imageScaling = NSImageScaleProportionallyUpOrDown;
    g_overlayView.imageAlignment = NSImageAlignCenter;
    g_overlayView.wantsLayer = YES;
    g_overlayView.layer.backgroundColor = NSColor.clearColor.CGColor;
    [g_overlayWin setContentView:g_overlayView];
}

static void center_overlay_on_window() {
    ensure_overlay_created();

    if (!g_overlayImage) {
        NSData* overlayData = [NSData dataWithBytesNoCopy:(void*)overlay_png length:overlay_png_len freeWhenDone:NO];
        g_overlayImage = [[NSImage alloc] initWithData:overlayData];
    }

    const double W = g_windowRect.size.width;
    const NSSize   imgSz = g_overlayImage ? g_overlayImage.size : NSMakeSize(100,100);
    const double   aspect = (imgSz.width > 0 ? (imgSz.height / imgSz.width) : 1.0);
    const double   targetW = std::max(80.0, W * g_overlayScale);
    const double   targetH = targetW * aspect;

    const CGFloat xTop = g_windowRect.origin.x + (W - targetW) * 0.5; // X same in both systems
    const CGFloat yTop = g_windowRect.origin.y + (g_windowRect.size.height - targetH) * 0.5;
    const CGFloat cocoaY = cocoaOriginY_FromTop(yTop, targetH);

    [g_overlayWin setFrame:NSMakeRect(xTop, cocoaY, targetW, targetH) display:NO];
    [g_overlayView setFrame:NSMakeRect(0, 0, targetW, targetH)];
    g_overlayView.image = g_overlayImage;
    [g_overlayWin orderFrontRegardless];
}

// ===== v17.2 Debug Window =====
static NSImage* nsimage_from_bgr(const cv::Mat& bgr) {
    if (bgr.empty()) return nil;
    cv::Mat rgba; cv::cvtColor(bgr, rgba, cv::COLOR_BGR2RGBA);
    const int w = rgba.cols, h = rgba.rows;
    const size_t stride = rgba.step;
    CGColorSpaceRef cs = CGColorSpaceCreateDeviceRGB();
    CFDataRef data = CFDataCreate(kCFAllocatorDefault, (const UInt8*)rgba.data, h * stride);
    CGDataProviderRef prov = CGDataProviderCreateWithCFData(data);
    CGImageRef img = CGImageCreate(w, h, 8, 32, stride, cs,
                                     kCGBitmapByteOrderDefault | kCGImageAlphaPremultipliedLast,
                                     prov, nullptr, false, kCGRenderingIntentDefault);
    NSImage* nsimg = [[NSImage alloc] initWithCGImage:img size:NSMakeSize(w,h)];
    CGImageRelease(img); CGDataProviderRelease(prov); CFRelease(data); CGColorSpaceRelease(cs);
    return nsimg;
}

static void ensure_debug_window_left_of_mirror() {
    if (!g_debugWin) {
        g_debugWin = [[DebugWindow alloc]
            initWithContentRect:NSMakeRect(50,50,g_dbgW,g_dbgH)
                      styleMask:NSWindowStyleMaskTitled | NSWindowStyleMaskClosable
                        backing:NSBackingStoreBuffered
                          defer:NO];
        g_debugWin.level = NSFloatingWindowLevel;
        g_debugWin.opaque = YES;
        g_debugWin.backgroundColor = NSColor.blackColor;

        g_debugView = [[NSImageView alloc] initWithFrame:NSMakeRect(0, 0, g_dbgW, g_dbgH)];
        g_debugView.imageScaling = NSImageScaleAxesIndependently;
        g_debugView.imageAlignment = NSImageAlignCenter;
        [g_debugWin setContentView:g_debugView];
    }

    CGFloat desiredX = g_windowRect.origin.x - g_dbgW - 16;
    if (desiredX < 10) desiredX = 10;
    CGFloat topY = g_windowRect.origin.y; // align tops
    CGFloat cocoaY = cocoaOriginY_FromTop(topY, g_dbgH);

    [g_debugWin setFrame:NSMakeRect(desiredX, cocoaY, g_dbgW, g_dbgH) display:NO];
    [g_debugWin orderFrontRegardless];
}

// v14.2 Note: This function now receives the METAL RADAR output (debugMat)
static void debug_draw_and_show(const cv::Mat& debugMat, const std::string& status) {
    cv::Mat vis;
    if (debugMat.empty()) {
        vis = cv::Mat(g_dbgH, g_dbgW, CV_8UC3, cv::Scalar(0,0,0));
    } else {
        // debugMat is 302x655 (RADAR_W x RADAR_H)
        double sx = (double)g_dbgW / debugMat.cols;
        double sy = (double)g_dbgH / debugMat.rows;
        double s = std::min(sx, sy);
        int nw = std::max(1, (int)std::round(debugMat.cols * s));
        int nh = std::max(1, (int)std::round(debugMat.rows * s));
        
        cv::Mat resizedMat;
        cv::resize(debugMat, resizedMat, cv::Size(nw,nh), 0, 0, cv::INTER_NEAREST); // Use INTER_NEAREST for sharp radar pixels
        
        // Ensure vis is 3-channel BGR for putText
        if (resizedMat.channels() == 4) {
            cv::cvtColor(resizedMat, vis, cv::COLOR_BGRA2BGR);
        } else if (resizedMat.channels() == 1) {
            cv::cvtColor(resizedMat, vis, cv::COLOR_GRAY2BGR);
        } else {
            vis = resizedMat.clone();
        }

        if (nw < g_dbgW || nh < g_dbgH) {
            cv::copyMakeBorder(vis, vis, 0, g_dbgH-nh, 0, g_dbgW-nw, cv::BORDER_CONSTANT, cv::Scalar(0,0,0));
        }
    }

    if (!status.empty()) {
        cv::putText(vis, status, {10, 24}, cv::FONT_HERSHEY_SIMPLEX, 0.6, cv::Scalar(255,255,255), 1, cv::LINE_AA);
    }

    NSImage* nsimg = nsimage_from_bgr(vis);
    g_debugView.image = nsimg;
}

// ===== v17.2 Splash Screen =====
static void destroy_splash(){
    if (g_splashPlayer) { [g_splashPlayer stop]; g_splashPlayer = nil; }
    if (g_splashWin) { [g_splashWin orderOut:nil]; g_splashWin = nil; g_splashLabel = nil; g_splashArtView = nil; g_splashArt = nil; }
}

static void play_splash_audio_once() {
    NSError* err = nil;
    NSData* audioData = [NSData dataWithBytesNoCopy:(void*)bodies_wav length:bodies_wav_len freeWhenDone:NO];
    g_splashPlayer = [[AVAudioPlayer alloc] initWithData:audioData error:&err];
    if (!g_splashPlayer || err) { std::cerr<<"[SPLASH] audio init failed\n"; return; }
    [g_splashPlayer prepareToPlay];
    g_splashPlayer.volume = 1.0;
    [g_splashPlayer play];
    std::cout << "[SPLASH] audio playing\n";
}

static void show_splash_then(std::function<void()> onDone){
    std::cout << "[SPLASH] showing splash\n";
    NSScreen* mainScr = NSScreen.mainScreen;
    const CGFloat screenW = mainScr.frame.size.width;
    const CGFloat screenH = mainScr.frame.size.height;

    // Make splash half the screen size and center it
    const CGFloat W = screenW / 2.0;
    const CGFloat H = screenH / 2.0;
    const CGFloat X = mainScr.frame.origin.x + (screenW - W) / 2.0;
    const CGFloat Y = mainScr.frame.origin.y + (screenH - H) / 2.0;

    NSData* splashData = [NSData dataWithBytesNoCopy:(void*)splash_png length:splash_png_len freeWhenDone:NO];
    g_splashArt = [[NSImage alloc] initWithData:splashData];

    g_splashWin = [[DeadeyeSplash alloc]
        initWithContentRect:NSMakeRect(X, Y, W, H)
                  styleMask:NSWindowStyleMaskBorderless
                    backing:NSBackingStoreBuffered
                      defer:NO];
    g_splashWin.opaque = YES;
    g_splashWin.backgroundColor = NSColor.blackColor;
    g_splashWin.level = NSStatusWindowLevel;
    g_splashWin.ignoresMouseEvents = YES;
    g_splashWin.collectionBehavior = NSWindowCollectionBehaviorCanJoinAllSpaces;

    NSView* content = [[NSView alloc] initWithFrame:NSMakeRect(0,0,W,H)];
    [g_splashWin setContentView:content];

    const CGFloat statusBarHeight = 80.0;

    g_splashArtView = [[NSImageView alloc] initWithFrame:NSMakeRect(0, statusBarHeight, W, H - statusBarHeight)];
    g_splashArtView.imageScaling = NSImageScaleProportionallyUpOrDown;
    g_splashArtView.imageAlignment = NSImageAlignCenter;
    g_splashArtView.wantsLayer = YES;
    g_splashArtView.layer.backgroundColor = NSColor.blackColor.CGColor;
    g_splashArtView.image = g_splashArt;
    [content addSubview:g_splashArtView];

    g_splashLabel = [[NSTextField alloc] initWithFrame:NSMakeRect(40, 24, W - 80, 40)];
    g_splashLabel.bezeled = NO;
    g_splashLabel.drawsBackground = NO;
    g_splashLabel.editable = NO;
    g_splashLabel.selectable = NO;
    g_splashLabel.alignment = NSTextAlignmentCenter;
    g_splashLabel.textColor = [NSColor colorWithRed:1 green:0 blue:0 alpha:1];
    if (@available(macOS 11.0, *)) {
        g_splashLabel.font = [NSFont monospacedSystemFontOfSize:28 weight:NSFontWeightBold];
    } else {
        g_splashLabel.font = [NSFont fontWithName:@"Menlo-Bold" size:28] ?: [NSFont boldSystemFontOfSize:28];
    }
    [content addSubview:g_splashLabel];

    [g_splashWin orderFrontRegardless];
    play_splash_audio_once();

    std::vector<std::string> seq = {
        "Initializing","Initializing.","Initializing..","Initializing...",
        "Starting..."
    };
    const double total = 3.0;  // 3 seconds for testing (was 25.0)
    const double step  = total / (double)seq.size();

    __block size_t idx = 0;
    __block dispatch_source_t timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, dispatch_get_main_queue());
    dispatch_source_set_timer(timer, DISPATCH_TIME_NOW, (uint64_t)(step * NSEC_PER_SEC), (uint64_t)(0.05 * NSEC_PER_SEC));
    dispatch_source_set_event_handler(timer, ^{
        if (g_quit.load()) { dispatch_source_cancel(timer); destroy_splash(); return; }
        if (idx < seq.size()) {
            g_splashLabel.stringValue = [NSString stringWithUTF8String:seq[idx].c_str()];
            idx++;
            if (idx == seq.size()) {
                dispatch_source_cancel(timer);
                dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.8 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                    destroy_splash();
                    if (onDone) onDone();
                });
            }
        }
    });
    dispatch_resume(timer);
}


// ============================================================================
// v14.2 METAL RADAR PIPELINE (Ported)
// ============================================================================
bool init_metal_pipeline(const std::string& execDir){
    std::string metalPath=execDir+"/RockGame.metal";
    if(!std::filesystem::exists(metalPath)) metalPath=execDir+"/../RockGame.metal";

    g_device=MTLCreateSystemDefaultDevice(); if(!g_device){ std::cerr<<"FATAL: no Metal device\n"; return false; }
    g_commandQueue=[g_device newCommandQueue]; if(!g_commandQueue){ std::cerr<<"FATAL: no command queue\n"; return false; }

    NSError* error=nil; std::ifstream mf(metalPath);
    if(!mf.is_open()){ std::cerr<<"FATAL: Could not open shader: "<<metalPath<<"\n"; return false; }
    std::string srcStr((std::istreambuf_iterator<char>(mf)), std::istreambuf_iterator<char>());
    NSString* src=[[NSString alloc] initWithBytes:srcStr.data() length:srcStr.size() encoding:NSUTF8StringEncoding];

    id<MTLLibrary> radarLibrary=[g_device newLibraryWithSource:src options:nil error:&error];
    if(!radarLibrary){ std::cerr<<"FATAL: shader compile failed\n"; return false; }
    id<MTLFunction> radarFunction=[radarLibrary newFunctionWithName:@"rockgameRadar"];
    if(!radarFunction){ std::cerr<<"FATAL: function rockgameRadar missing\n"; return false; }
    g_radarPipeline=[g_device newComputePipelineStateWithFunction:radarFunction error:&error];
    if(!g_radarPipeline){ std::cerr<<"FATAL: pipeline create failed\n"; return false; }

    MTLTextureDescriptor* td=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:RADAR_WIDTH height:RADAR_HEIGHT mipmapped:NO];
    td.usage=MTLTextureUsageShaderRead | MTLTextureUsageShaderWrite; g_debugTexture=[g_device newTextureWithDescriptor:td];

    g_constantsBuffer=[g_device newBufferWithLength:sizeof(int)*3 options:MTLResourceStorageModeShared];
    int* c=(int*)[g_constantsBuffer contents]; c[0]=DESTROY_PIT_Y; c[1]=UI_TIMER_Y_LIMIT; c[2]=UI_SCORE_Y_LIMIT;
    std::cout<<"[Metal] Radar initialized\n";
    return true;
}

void run_radar_on_pair(id<MTLTexture> cur,id<MTLTexture> prev){
    @autoreleasepool {
        id<MTLCommandBuffer> cmd=[g_commandQueue commandBuffer];
        id<MTLComputeCommandEncoder> enc=[cmd computeCommandEncoder];
        [enc setComputePipelineState:g_radarPipeline];
        [enc setTexture:cur atIndex:0]; [enc setTexture:prev atIndex:1]; [enc setTexture:g_debugTexture atIndex:2];
        [enc setBuffer:g_constantsBuffer offset:0 atIndex:0];
        MTLSize thr=MTLSizeMake(RADAR_WIDTH,RADAR_HEIGHT,1), tpt=MTLSizeMake(8,8,1);
        [enc dispatchThreads:thr threadsPerThreadgroup:tpt]; [enc endEncoding]; [cmd commit]; [cmd waitUntilCompleted];
    }
}

id<MTLTexture> cv_to_texture(const cv::Mat& bgr){
    cv::Mat rgba; cv::cvtColor(bgr,rgba,cv::COLOR_BGR2RGBA);
    MTLTextureDescriptor* d=[MTLTextureDescriptor texture2DDescriptorWithPixelFormat:MTLPixelFormatRGBA8Unorm width:rgba.cols height:rgba.rows mipmapped:NO];
    d.usage=MTLTextureUsageShaderRead; id<MTLTexture> t=[g_device newTextureWithDescriptor:d];
    MTLRegion R=MTLRegionMake2D(0,0,rgba.cols,rgba.rows); [t replaceRegion:R mipmapLevel:0 withBytes:rgba.data bytesPerRow:rgba.step];
    return t;
}


// ============================================================================
// v14.2 DETECTION (Ported)
// ============================================================================
struct ButtonCand{ cv::Rect r; cv::Point c; double area; };

static std::vector<ButtonCand> find_orange_buttons(const cv::Mat& bgr){
    std::vector<ButtonCand> out; if(bgr.empty()) return out;
    cv::Mat hsv,mask; cv::cvtColor(bgr,hsv,cv::COLOR_BGR2HSV);
    cv::inRange(hsv, ORANGE_LOW, ORANGE_HIGH, mask); // Use v14.2's ORANGE
    cv::morphologyEx(mask,mask,cv::MORPH_CLOSE,cv::getStructuringElement(cv::MORPH_RECT, cv::Size(9,9)));
    std::vector<std::vector<cv::Point>> cnt; cv::findContours(mask,cnt,cv::RETR_EXTERNAL,cv::CHAIN_APPROX_SIMPLE);
    for(const auto& c: cnt){
        double a=cv::contourArea(c); if(a<800) continue;
        cv::Rect r=cv::boundingRect(c);
        if(r.width > bgr.cols*0.9 || r.height > bgr.rows*0.4) continue;
        out.push_back({r, cv::Point(r.x+r.width/2, r.y+r.height/2), a});
    }
    std::sort(out.begin(),out.end(),[](auto&A,auto&B){return A.c.y < B.c.y;}); // top→bottom
    return out;
}

static cv::Point find_cannon_start(const cv::Mat& bgr){
    if(bgr.empty()) return {-1,-1};
    cv::Mat hsv,mask; cv::cvtColor(bgr,hsv,cv::COLOR_BGR2HSV);
    cv::inRange(hsv, CANNON_HSV_LOW, CANNON_HSV_HIGH, mask);
    int yMin=(int)std::floor(bgr.rows*0.60);
    if(yMin < mask.rows) mask.rowRange(0,yMin).setTo(0);
    cv::morphologyEx(mask,mask,cv::MORPH_CLOSE,cv::getStructuringElement(cv::MORPH_RECT, cv::Size(7,7)));
    std::vector<std::vector<cv::Point>> cnt; cv::findContours(mask,cnt,cv::RETR_EXTERNAL,cv::CHAIN_APPROX_SIMPLE);
    double bestA=0; cv::Rect best;
    for(const auto& c: cnt){
        double a=cv::contourArea(c); if(a<120 || a>12000) continue;
        if(a>bestA){ bestA=a; best=cv::boundingRect(c); }
    }
    if(best.width==0) return {-1,-1};
    // v14.2 used a +30 offset, v17.2 has one. Let's keep v17.2's.
    return {best.x + best.width/2, best.y + best.height/2 + 30};
}

// v14.2 Live Cannon Tracker (Ported)
float track_cannon_live(const cv::Mat& f){
    int y0=(int)(f.rows*0.60); cv::Rect roi(0,y0,f.cols,f.rows-y0); if(roi.height<=0) return -1;
    cv::Mat c=f(roi).clone();
    cv::Mat hsv,mask; cv::cvtColor(c,hsv,cv::COLOR_BGR2HSV); cv::inRange(hsv,CANNON_HSV_LOW,CANNON_HSV_HIGH,mask);
    cv::morphologyEx(mask,mask,cv::MORPH_OPEN,cv::getStructuringElement(cv::MORPH_RECT,{5,5}));
    cv::morphologyEx(mask,mask,cv::MORPH_CLOSE,cv::getStructuringElement(cv::MORPH_RECT,{7,7}));
    std::vector<std::vector<cv::Point>> cnt; cv::findContours(mask,cnt,cv::RETR_EXTERNAL,cv::CHAIN_APPROX_SIMPLE);
    if(cnt.empty()) return -1;
    double bestA=0; cv::Rect best;
    for(const auto& cc: cnt){
        cv::Rect r=cv::boundingRect(cc);
        if(r.height < 20 || r.width < 20) continue;
        double a=cv::contourArea(cc);
        if(a>bestA){ bestA=a; best=r; }
    }
    if(bestA<=0) return -1;
    float cx = best.x + best.width/2.0f;
    return cx;
}


// ============================================================================
// v14.2 BOT BRAIN (Ported)
// ============================================================================
void update_bullets(float dt){
    for(auto& b: g_bullets){ if(!b.active) continue; b.y+=b.vy*dt; if(b.y<0) b.active=false; }
    g_bullets.erase(std::remove_if(g_bullets.begin(),g_bullets.end(),[](const BulletState&b){return !b.active;}), g_bullets.end());
}

void fire_bullet(float cx,double ts){
    if(ts-g_last_fire_time<1.0/FIRE_RATE) return;
    BulletState b; b.id=g_next_bullet_id++; b.x=cx; b.y=CANNON_GROUND_Y-CANNON_HEIGHT/2; b.vx=0; b.vy=-BULLET_SPEED; b.fired_time=ts; b.active=true;
    g_bullets.push_back(b); g_last_fire_time=ts; 
    std::lock_guard<std::mutex> lk(g_log_mutex);
    g_bullet_log<<ts<<","<<b.id<<","<<b.x<<","<<b.y<<"\n";
}

TrajectoryPrediction predict_full_trajectory(const RockState& r){
    TrajectoryPrediction pred; 
    float x=r.center.x, y=r.center.y, vx=r.velocity.x, vy=r.velocity.y; 
    const float dt=1.0f/60.0f, T=10.0f; 
    float t=0.0f; 
    pred.min_x=x; pred.max_x=x; 
    int b=0, B=50;
    
    while(t<T && b<B){
        vy+=GRAVITY*dt; 
        x+=vx*dt; 
        y+=vy*dt; 
        pred.min_x=std::min(pred.min_x,x); 
        pred.max_x=std::max(pred.max_x,x);
        
        if(x<=0.0f){ 
            x=0.0f; 
            vx=std::abs(vx)*ROCK_BOUNCE_DAMPING; 
            pred.bounces.push_back({x,y,t,BouncePoint::WALL_LEFT}); 
            b++; 
        }
        if(x>=RADAR_WIDTH){ 
            x=RADAR_WIDTH; 
            vx=-std::abs(vx)*ROCK_BOUNCE_DAMPING; 
            pred.bounces.push_back({x,y,t,BouncePoint::WALL_RIGHT}); 
            b++; 
        }
        if(y>=CANNON_GROUND_Y){ 
            y=CANNON_GROUND_Y; 
            vy=-std::abs(vy)*ROCK_BOUNCE_DAMPING; 
            pred.bounces.push_back({x,y,t,BouncePoint::GROUND}); 
            pred.ground_crossings.push_back({t,x}); 
            b++; 
            if(std::abs(vy)<10.0f){ 
                pred.is_stable=true; 
                break; 
            } 
        }
        t+=dt;
    } 
    return pred;
}

void check_bullet_hits(){
    for(auto& b: g_bullets){
        if(!b.active) continue;
        for(auto& [id,r]: g_rock_database){
            CollisionBox bb={b.x-5,b.x+5,b.y-10,b.y+10};
            if(bb.overlaps(r.get_collision_box())){ 
                r.hp--; 
                b.active=false;
                if(r.hp<=0){
                    g_last_destroyed_hp=r.original_hp;
                    // Split logic: Large and Medium rocks split, Small rocks don't
                    if((r.size == RockSize::LARGE || r.size == RockSize::MEDIUM) && !r.is_split_child){
                        g_pending_split_children=2;
                        g_split_child_hp=r.original_hp/2;
                    }
                }
                break;
            }
        }
    }
}

// Helper: Determine rock size from bounding box
RockSize getRockSize(const cv::Rect& bbox) {
    int size = std::max(bbox.width, bbox.height);
    if (size < 100) {
        return RockSize::SMALL;      // ~50px
    } else if (size < 215) {
        return RockSize::MEDIUM;     // ~175px
    } else {
        return RockSize::LARGE;      // ~250px
    }
}

void update_rock_database(cv::Mat& radar,double ts,float dt){
    std::vector<cv::Mat> ch(4); cv::split(radar,ch);
    cv::Mat red=ch[2], green=ch[1];
    std::vector<std::vector<cv::Point>> cont;
    cv::findContours(red,cont,cv::RETR_EXTERNAL,cv::CHAIN_APPROX_SIMPLE);

    std::vector<RockState> det;
    for(const auto& c: cont){
        double area = cv::contourArea(c);

        // Filter 1: Area must be at least 1000px (small rock ~2500px)
        if(area < 1000.0) continue;

        // Filter 2: Area can't be huge (large rock ~62500px, add margin)
        if(area > 70000.0) continue;

        cv::Rect bb=cv::boundingRect(c);

        // Filter 3: Bounding box size must be reasonable (30-300px)
        int maxDim = std::max(bb.width, bb.height);
        if(maxDim < 30 || maxDim > 300) continue;

        // Filter 4: Must be roughly square (aspect ratio 0.5 to 2.0)
        float aspect = static_cast<float>(bb.width) / std::max(1, bb.height);
        if(aspect < 0.5f || aspect > 2.0f) continue;

        // Filter 5: Ignore things near cannon level (Y > 580)
        cv::Point2f center(bb.x+bb.width/2.0f, bb.y+bb.height/2.0f);
        if(center.y > 580.0f) continue;

        // Passed all filters - this is a real rock
        int hpix=cv::countNonZero(green(bb));
        RockState d;
        d.bbox=bb;
        d.center=center;
        d.last_seen=ts;
        d.hp=(hpix>5)? g_last_destroyed_hp+1 : 1;
        d.size = getRockSize(bb);  // Classify size
        det.push_back(d);
    }
    
    std::map<int,RockState> next; 
    std::vector<char> m(det.size(),0);
    
    for(auto& [id,o]: g_rock_database){
        float best=100.f; int k=-1;
        for(size_t i=0;i<det.size();++i){ 
            if(m[i]) continue; 
            float dist=cv::norm(det[i].center - o.center); 
            if(dist<best){ 
                best=dist; 
                k=(int)i; 
            } 
        }
        if(k>=0){
            m[k]=1; 
            RockState& r=det[k];
            if(dt>0.001f){ 
                r.velocity.x=(r.center.x-o.center.x)/dt; 
                r.velocity.y=(r.center.y-o.center.y)/dt; 
            } else {
                r.velocity=o.velocity;
            }
            r.id=o.id;
            r.hp=o.hp;
            r.original_hp=o.original_hp;
            r.is_tracked=true;
            r.is_split_child=o.is_split_child;
            // Note: r.size was already set by getRockSize() above, keep the fresh measurement
            r.type=(r.center.y < FALLING_THRESHOLD_Y)? 
                   RockState::Type::FALLING : 
                   (r.center.y >= CANNON_GROUND_Y-30? RockState::Type::LANDED : RockState::Type::FALLING);
            TrajectoryPrediction t=predict_full_trajectory(r);
            if(!t.ground_crossings.empty()){ 
                r.time_to_ground=t.ground_crossings[0].first; 
                r.predicted_x=t.ground_crossings[0].second; 
            } else { 
                r.time_to_ground=999.f; 
                r.predicted_x=r.center.x; 
            }
            next[r.id]=r;
        } else { 
            g_last_destroyed_hp=o.hp; 
        }
    }
    
    for(size_t i=0;i<det.size();++i){
        if(m[i]) continue;
        RockState r=det[i]; 
        r.id=g_next_rock_id++; 
        r.velocity=cv::Point2f(0,0); 
        r.is_tracked=false; 
        r.type=RockState::Type::FALLING;
        
        if(g_pending_split_children>0){ 
            r.hp=g_split_child_hp; 
            r.original_hp=g_split_child_hp; 
            r.is_split_child=true; 
            g_pending_split_children--; 
        } else { 
            r.hp=g_last_destroyed_hp+1; 
            r.original_hp=r.hp; 
            r.is_split_child=false; 
        }
        
        TrajectoryPrediction t=predict_full_trajectory(r);
        if(!t.ground_crossings.empty()){ 
            r.time_to_ground=t.ground_crossings[0].first; 
            r.predicted_x=t.ground_crossings[0].second; 
        } else { 
            r.time_to_ground=999.f; 
            r.predicted_x=r.center.x; 
        }
        next[r.id]=r;
    }
    g_rock_database.swap(next);
}

std::vector<SafeZone> find_safe_camping_zones(){
    const int W=RADAR_WIDTH; 
    const float HZN=5.0f; 
    const int SL=50; 
    const float DT=HZN/SL;
    
    std::vector<std::vector<bool>> occ(SL,std::vector<bool>(W,false));
    
    for(const auto& [id,r]: g_rock_database){
        TrajectoryPrediction tr=predict_full_trajectory(r);
        for(const auto& p: tr.ground_crossings){
            float tt=p.first, xx=p.second; 
            if(tt>HZN) continue;
            int s=(int)(tt/DT); 
            if(s>=SL) continue;
            int xmin=std::max(0,(int)(xx-CANNON_WIDTH/2.0f)); 
            int xmax=std::min(W,(int)(xx+CANNON_WIDTH/2.0f));
            for(int x=xmin;x<xmax;x++) occ[s][x]=true;
        }
    }
    
    std::vector<bool> safe(W,true);
    for(int x=0;x<W;x++){ 
        for(int t=0;t<SL;t++){ 
            if(occ[t][x]){ 
                safe[x]=false; 
                break; 
            } 
        } 
    }
    
    std::vector<SafeZone> zones; 
    int st=-1;
    for(int x=CANNON_WIDTH/2;x<W-CANNON_WIDTH/2;x++){
        if(safe[x]){ 
            if(st==-1) st=x; 
        } else { 
            if(st!=-1){ 
                SafeZone z; 
                z.x_min=st; 
                z.x_max=x; 
                z.x_center=(z.x_min+z.x_max)/2.0f; 
                z.width=z.x_max-z.x_min; 
                z.is_permanent=true; 
                z.safe_until=999.0; 
                if(z.width>=MIN_SAFE_GAP) zones.push_back(z); 
                st=-1; 
            } 
        }
    }
    return zones;
}

SafeZone find_best_safe_zone(float cx,const std::vector<SafeZone>& z){
    if(z.empty()) return {cx,cx-10,cx+10,20,false,0.0};
    const SafeZone* best=nullptr; 
    float md=1e9f;
    for(const auto& s: z){ 
        float d=std::abs(s.x_center-cx); 
        if(d<md){ 
            md=d; 
            best=&s; 
        } 
    }
    return best?*best:z[0];
}

BotDecision decide(float cannon_x_rel){
    BotDecision d;
    auto zones=find_safe_camping_zones();
    
    // Imminent threat check
    bool imminent=false;
    for(const auto& [id,r]: g_rock_database){
        if(r.time_to_ground<PANIC_TIME){
            float dist=std::abs(r.predicted_x-cannon_x_rel);
            if(dist<CANNON_WIDTH){ 
                imminent=true; 
                break; 
            }
        }
    }
    
    if(imminent){
        d.priority="P0_EMERGENCY"; 
        d.strategy="DODGE"; 
        d.decision="EMERGENCY_MOVE";
        auto best=find_best_safe_zone(cannon_x_rel,zones);
        d.target_x_rel=best.x_center;
        return d;
    }

    int total=(int)g_rock_database.size();
    if(total<LOW_THREAT_THRESHOLD && zones.size()>3){
        d.priority="P1_OFFENSE"; 
        d.strategy="HUNT";
        RockState* w=nullptr; 
        int mh=9999;
        for(auto& [id,r]: g_rock_database){ 
            if(r.is_falling() && r.hp<mh){ 
                mh=r.hp; 
                w=&r; 
            } 
        }
        if(w){ 
            d.decision="CHASE_WEAKEST"; 
            d.target_x_rel=w->predicted_x; 
        } else { 
            d.strategy="CAMP"; 
            d.decision="NO_TARGETS"; 
            auto best=find_best_safe_zone(cannon_x_rel,zones); 
            d.target_x_rel=best.x_center; 
        }
    } else {
        d.priority="P1_DEFENSE"; 
        d.strategy="CAMP";
        auto best=find_best_safe_zone(cannon_x_rel,zones);
        bool in=false; 
        for(const auto& z: zones){ 
            if(cannon_x_rel>=z.x_min && cannon_x_rel<=z.x_max){ 
                in=true; 
                break; 
            } 
        }
        if(in){ 
            d.decision="STAY_IN_ZONE"; 
            d.target_x_rel=cannon_x_rel; 
        } else { 
            d.decision="MOVE_TO_SAFE_ZONE"; 
            d.target_x_rel=best.x_center; 
        }
    }
    return d;
}

// v14.2 Cannon Watchdog (Ported)
void ensure_drag_control(float observed_x_rel, float desired_x_rel, bool imminent){
    // Detect "no movement"
    if(g_last_observed_x_rel>=0 && std::abs(observed_x_rel - g_last_observed_x_rel) <= 2.0f){
        g_no_movement_frames++;
    } else {
        g_no_movement_frames = 0;
    }
    g_last_observed_x_rel = observed_x_rel;

    bool far_from_target = std::abs(desired_x_rel - observed_x_rel) > 15.0f;
    bool rocks_exist = !g_rock_database.empty();

    if((imminent || (rocks_exist && g_no_movement_frames > 45) || (far_from_target && g_no_movement_frames > 20)) && g_rehold_cooldown==0){
        // v14.2: We need the absolute Y of the cannon
        // This is fine, as g_cannon_y_abs is set by click_and_hold.
        release_mouse();
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
        click_and_hold(g_windowRect.origin.x + observed_x_rel, g_cannon_y_abs);
        g_rehold_cooldown = 30; // ~1.0s at 30fps
        std::cerr<<"[RECOVER] Re-held at observed X="<<observed_x_rel<<"\n";
    }
    if(g_rehold_cooldown>0) g_rehold_cooldown--;
}


// ============================================================================
// v17.4 ASYNC STARTUP (Replaces v14.2's blocking `perform_startup_sequence`)
// ============================================================================

// This is the 45Hz bot logic loop, moved from main()
void start_bot_logic_timer() {
    log_line("Startup OK. Cannon holding. Starting bot logic loop...");

    // [v14.2] Bot logic state
    __block cv::Mat debugMat(RADAR_HEIGHT, RADAR_WIDTH, CV_8UC4, cv::Scalar(0,0,0,255));
    __block auto last_logic_time = std::chrono::steady_clock::now();
    __block long frame_count = 0;

    const double bot_fps = 45.0;
    g_bot_logic_timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, dispatch_get_main_queue());
    dispatch_source_set_timer(g_bot_logic_timer, DISPATCH_TIME_NOW, (uint64_t)( (1.0/bot_fps) * NSEC_PER_SEC), (uint64_t)(0.01 * NSEC_PER_SEC));
    dispatch_source_set_event_handler(g_bot_logic_timer, ^{
        @autoreleasepool {
            if (g_quit.load()) {
                dispatch_source_cancel(g_bot_logic_timer);
                return;
            }
            
            // --- v17.2: UI / Window Tracking ---
            WindowInfo cur = find_window_info(WINDOW_TITLE.c_str());
            if(cur.valid && (cur.rect.origin.x != g_windowRect.origin.x || cur.rect.origin.y != g_windowRect.origin.y)) {
                g_windowRect = cur.rect;
                center_overlay_on_window();
                ensure_debug_window_left_of_mirror();
            }

            // --- v14.2: Bot Logic (All ported) ---
            double ts = nowSec();
            auto now = std::chrono::steady_clock::now();
            float dt = std::chrono::duration<float>(now - last_logic_time).count();
            last_logic_time = now;
            
            cv::Mat currentFrameCV = g_cap.latest_cropped_downscaled(); 
            if(currentFrameCV.empty()) return;

            float obs_x = track_cannon_live(currentFrameCV);
            if(obs_x>=0) g_observed_cannon_x_rel = obs_x;

            id<MTLTexture> curTex = cv_to_texture(currentFrameCV);
            if(g_lastFrameTexture){ 
                run_radar_on_pair(curTex, g_lastFrameTexture); 
            }
            MTLRegion region=MTLRegionMake2D(0,0,RADAR_WIDTH,RADAR_HEIGHT);
            [g_debugTexture getBytes:debugMat.data bytesPerRow:RADAR_WIDTH*4 fromRegion:region mipmapLevel:0];

            // radar output is BGRA, bot needs BGR for some CV ops
            cv::cvtColor(debugMat, debugMat, cv::COLOR_BGRA2BGR); 

            update_rock_database(debugMat, ts, dt); 
            update_bullets(dt); 
            check_bullet_hits();

            {
                std::lock_guard<std::mutex> lk(g_log_mutex);
                for(auto const& [id,r]: g_rock_database){
                    g_rock_log<<ts<<","<<id<<","<<r.center.x<<","<<r.center.y<<","
                             <<r.velocity.x<<","<<r.velocity.y<<","<<r.hp<<","
                             <<r.original_hp<<","<<r.time_to_ground<<","<<r.predicted_x<<"\n";
                }
            }

            float cannon_x = g_observed_cannon_x_rel;
            BotDecision dec = decide(cannon_x);

            bool imminent=false;
            for(const auto& [id,r]: g_rock_database){
                if(r.time_to_ground<PANIC_TIME && std::abs(r.predicted_x-cannon_x)<CANNON_WIDTH){ 
                    imminent=true; break; 
                }
            }

            {
                std::lock_guard<std::mutex> lk(g_log_mutex);
                g_bot_log<<ts<<","<<cannon_x<<","<<g_rock_database.size()<<","
                        <<dec.priority<<","<<dec.strategy<<","<<dec.decision<<","
                        <<dec.target_x_rel<<"\n";
            }

            move_mouse(g_windowRect.origin.x + dec.target_x_rel, g_cannon_y_abs);
            keep_mouse_held();
            ensure_drag_control(cannon_x, dec.target_x_rel, imminent);

            std::string status_str = "LIVE: " + dec.strategy + " | " + dec.decision;
            debug_draw_and_show(debugMat, status_str);
            
            g_lastFrameTexture = curTex; // ARC will handle the old one
            frame_count++;
            
            if(frame_count%60==0) {
                log_line("[Frame "+std::to_string(frame_count)+
                         "] Rocks: "+std::to_string(g_rock_database.size())+
                         " | "+dec.strategy+" | "+dec.decision);
            }
        } // end @autoreleasepool
    });
    dispatch_resume(g_bot_logic_timer);
}


// This is the new, NON-BLOCKING startup sequence
void start_startup_sequence_timer() {
    log_line("=== ASYNC STARTUP SEQUENCE ===");
    
    // This timer runs at 10Hz to check for buttons/cannon
    const double startup_fps = 10.0;
    g_startup_timer = dispatch_source_create(DISPATCH_SOURCE_TYPE_TIMER, 0, 0, dispatch_get_main_queue());
    dispatch_source_set_timer(g_startup_timer, DISPATCH_TIME_NOW, (uint64_t)( (1.0/startup_fps) * NSEC_PER_SEC), (uint64_t)(0.01 * NSEC_PER_SEC));
    dispatch_source_set_event_handler(g_startup_timer, ^{
        @autoreleasepool {
            if (g_quit.load()) {
                dispatch_source_cancel(g_startup_timer);
                return;
            }

            // Always update window rect
            WindowInfo info = find_window_info(WINDOW_TITLE.c_str());
            if(info.valid) g_windowRect = info.rect;
            else {
                log_line("Startup failed: Window lost");
                g_quit.store(true);
                return;
            }
            
            // Always get latest frame
            cv::Mat f = g_cap.latest_cropped_downscaled();
            if (f.empty()) return; // Try again next tick

            // --- STATE MACHINE ---
            
            if (g_startupState == StartupState::LookingForButton) {
                auto btns = find_orange_buttons(f);
                debug_draw_and_show(cv::Mat(), "Looking for 'Play' (2nd)...");

                if (btns.size() >= 2) {
                    g_foundButtonRect = btns[1].r;  // Get and save the second button
                    
                    int fx = g_foundButtonRect.x + (int)(g_foundButtonRect.width * BUTTON_X_BIAS_FRAC); // 0.5
                    int fy = g_foundButtonRect.y + g_foundButtonRect.height/2 + (int)BUTTON_Y_OFFSET_PX; // 0.0
                    CGFloat sx = wx(fx);
                    CGFloat sy = wy_event(fy);

                    log_line("Clicking 2nd button (v14.2 Centered) at screen(" + std::to_string((int)sx) + "," + std::to_string((int)sy) + ")");
                    
                    activate_app_by_pid(info.pid);
                    move_mouse(sx, sy);
                    std::this_thread::sleep_for(120ms); // Short sleep for mouse move is ok
                    click_once(sx, sy);
                    
                    // Transition to next state
                    g_startupState = StartupState::ButtonClicked;
                    g_startupRetryCheckTime = nowSec() + 0.3; // Wait 300ms before checking for retry
                }
                // If button not found, just wait for next tick

            } else if (g_startupState == StartupState::ButtonClicked) {
                if (nowSec() < g_startupRetryCheckTime) return; // Wait for retry time to elapse

                auto buttons2 = find_orange_buttons(f);
                bool still_there = false;
                if(buttons2.size() >= 2) {
                    std::sort(buttons2.begin(), buttons2.end(), [](auto&A,auto&B){return A.c.y < B.c.y;});
                    if(std::abs(buttons2[1].r.x - g_foundButtonRect.x) < 10 &&
                       std::abs(buttons2[1].r.y - g_foundButtonRect.y) < 10) {
                        still_there = true;
                    }
                }
                
                if(still_there) {
                    int fx = g_foundButtonRect.x + (int)(g_foundButtonRect.width * BUTTON_X_BIAS_FRAC);
                    int fy = g_foundButtonRect.y + g_foundButtonRect.height/2 + (int)BUTTON_Y_OFFSET_PX;
                    CGFloat sx = wx(fx);
                    CGFloat sy = wy_event(fy);
                    
                    log_line("Button still present, retry click at (" + std::to_string((int)sx) + "," + std::to_string((int)sy) + ")");
                    move_mouse(sx, sy);
                    std::this_thread::sleep_for(100ms);
                    click_once(sx, sy);
                }
                
                // Transition to next state
                g_startupState = StartupState::LookingForCannon;
                log_line("Waiting for transition to game screen...");

            } else if (g_startupState == StartupState::LookingForCannon) {
                cv::Point cannon = find_cannon_start(f);
                debug_draw_and_show(cv::Mat(), "Searching for cannon…");

                if (cannon.x >= 0) {
                    // --- FOUND CANNON! ---
                    CGFloat cannon_abs_x = wx(cannon.x);
                    CGFloat cannon_abs_y = wy_event(cannon.y);
                    g_cannon_y_abs = cannon_abs_y; // Save the absolute Y
                    
                    click_and_hold(cannon_abs_x, cannon_abs_y);
                    
                    g_observed_cannon_x_rel = cannon.x;
                    g_last_observed_x_rel   = cannon.x;
                    
                    debug_draw_and_show(cv::Mat(), "CANNON: HOLDING");
                    
                    // --- Transition to DONE ---
                    g_startupState = StartupState::Done;
                    log_line("Startup OK. Cannon holding.");

                    // Stop this startup timer
                    dispatch_source_cancel(g_startup_timer);
                    
                    // --- START THE REAL BOT LOGIC LOOP ---
                    start_bot_logic_timer();
                }
                // If cannon not found, just wait for next tick
            }
            
        } // end @autoreleasepool
    });
    dispatch_resume(g_startup_timer);
}

// ============================================================================
// v17.2 KILL SWITCH
// ============================================================================
static void release_mouse_now() {
    CGPoint p = currentMouse();
    release_mouse(); // Use our v14.2 function
}
static CGEventRef tap_cb(CGEventTapProxy, CGEventType type, CGEventRef e, void*){
    if(type==kCGEventTapDisabledByTimeout || type==kCGEventTapDisabledByUserInput){
        if(g_tap) CGEventTapEnable(g_tap,true);
        return e;
    }
    if(type==kCGEventKeyDown){
        auto code=(CGKeyCode)CGEventGetIntegerValueField(e,kCGKeyboardEventKeycode);
        if(code==kVK_ANSI_X){
            g_quit.store(true);
            // v17.2's `[NSApp terminate:nil]` is cleaner, let's use it
            dispatch_async(dispatch_get_main_queue(), ^{ release_mouse_now(); [NSApp terminate:nil]; });
        }
    }
    return e;
}
static void start_key_thread(){
    g_tap = CGEventTapCreate(kCGSessionEventTap, kCGHeadInsertEventTap,
                               kCGEventTapOptionListenOnly, CGEventMaskBit(kCGEventKeyDown),
                               tap_cb, nullptr);
    if(!g_tap) return;
    g_tapSrc = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, g_tap, 0);
    std::thread([](){
        @autoreleasepool {
            CFRunLoopRef rl=CFRunLoopGetCurrent();
            CFRunLoopAddSource(rl, g_tapSrc, kCFRunLoopCommonModes);
            CGEventTapEnable(g_tap, true);
            CFRunLoopRun();
        }
    }).detach();
}
static void stop_kill_switch(){
    if(g_tap) CGEventTapEnable(g_tap,false);
    if(g_tapSrc){ CFRunLoopSourceInvalidate(g_tapSrc); CFRelease(g_tapSrc); g_tapSrc=nullptr; }
    if(g_tap){ CFMachPortInvalidate(g_tap); CFRelease(g_tap); g_tap=nullptr; }
}


// ============================================================================
// MAIN (v17.4 - Refactored Async Startup)
// ============================================================================
int main(int argc, char** argv){
    // [v14.8 FIX] Wrap entire main function body in an autorelease pool
    @autoreleasepool {
    
    [NSApplication sharedApplication];
    [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular];
    [NSApp activateIgnoringOtherApps:YES];

    std::cout << "=== DeadeyeBot v17.4 — THE ASYNC FIX ===\n";
    std::string execDir=std::filesystem::path(argv[0]).parent_path().string();

    // [v14.2] Open log files
    g_rock_log.open(CSV_ROCK_LOG);   
    g_rock_log<<"timestamp,rock_id,x,y,vx,vy,hp,original_hp,time_to_ground,predicted_x\n";
    g_bot_log.open(CSV_BOT_LOG);     
    g_bot_log<<"timestamp,cannon_x,total_rocks,priority,strategy,decision,target_x\n";
    g_bullet_log.open(CSV_BULLET_LOG); 
    g_bullet_log<<"timestamp,bullet_id,x,y\n";

    // [v14.2] Start Metal
    if(!init_metal_pipeline(execDir)){ 
        return 1; 
    }

    // [v17.2] Start kill switch
    start_key_thread();

    // [v17.2] Locate mirror and set rect
    WindowInfo win = find_window_info(WINDOW_TITLE.c_str());
    if(!win.valid){ std::cerr<<"FATAL: '"<<WINDOW_TITLE<<"' not found.\n"; return 1; }
    g_windowRect = win.rect;
    activate_app_by_pid(win.pid);

    // [v17.2] Prepare UI (overlay + debug)
    center_overlay_on_window();
    ensure_debug_window_left_of_mirror();
    
    // [v17.2] Start capture
    if(!g_cap.start()){ std::cerr<<"ERROR: screen capture start failed\n"; return 1; }

    // [v17.4] Splash FIRST; when done → start ASYNC startup sequence
    show_splash_then([&](){
        start_startup_sequence_timer();
    });

    // [v17.2] Run the main application loop
    [NSApp run];
    
    // Cleanup
    log_line("...Shutdown signal received...");
    g_quit.store(true);
    if(g_startup_timer) dispatch_source_cancel(g_startup_timer);
    if(g_bot_logic_timer) dispatch_source_cancel(g_bot_logic_timer);
    release_mouse_now();
    stop_kill_switch();
    g_rock_log.close(); 
    g_bot_log.close(); 
    g_bullet_log.close(); 
    log_line("DeadeyeBot shutdown complete.");
    
    } // end main @autoreleasepool
    return 0;
}